### ISSUE TITLE
Group members

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#1]
Hey all,

Since I do not use social media I have no other ways to reach out to my new group members than making an issue I guess. I am in group 12. My email address is wouter.mostard@gmail.com on which you can reach me to exchange numbers for communication :) 

Cheers,

Wouter

**Comment by rm-bwana** [comment]
We appreciate the enthusiasm and pro-activeness, we will be sending emails out to all group members using the @student.rug.nl email accounts and you can discuss further from there.
