### ISSUE TITLE
Exploratory and descriptive analysis

### ISSUE THREAD

**Issue by TimmermanIDS** [RUG-IDS/Course-2017#11]
Dear TAs,

We have got a question about the exploratory analysis and the descriptive questions. 

- Is the exploratory analysis used to investigate the values for each feature seperately? This is what I suspect since the b-part of the question asks to provide figures to answer the question. 

- We are a bit confused what falls under exploratory analysis and what under descriptive analysis

Kind regards,
Team-9

**Comment by rm-bwana** [comment]
1. Exploratory analysis is not limited to a certain number of features. You can look at features independently or in combination with others. Instead it tries to find relationships between or within features e.g. patterns and trends. Importantly it does **not** generalise i.e. summarise 

2. Descriptive analysis tries to find **generalisations** of the data at hand. 

Both can be adequately (and probably best) shown via figure as shown in the lecture slides.
