### ISSUE TITLE
Presentation schedule

### ISSUE THREAD

**Issue by sietzehouwink** [RUG-IDS/Course-2017#14]
Dear reader,

The presentation has to last 30 minutes, and there are about 15 groups. Will the presentations therefore be in parallel, and when will the schedule for that be available?

Yours sincerely,
Sietze Houwink

**Comment by rm-bwana** [comment]
Hi Sietze,

The general idea is that the teams will be split into 5 different rooms each with 3 teams. Each one of the 3 teams per room would have covered an individual topic as in the assignment. 
Each team will then present their topic to the 2 other teams in the room as well as one of the TAs or course lecturers. 
This will all be completed within the 2 hour lecture time on Monday 18th. The exact schedule will be posted here on Github as well as announced on Nestor once it is finalised with the room allocations. 

Yours,
The reader

**Comment by rm-bwana** [comment]
The information has now been posted. All teams should be present in their respective rooms as announced by the start of the lecture time (11am) on Monday. 

All the best,
Same reader as before.
