### ISSUE TITLE
Paper by Cover

### ISSUE THREAD

**Issue by marialeyva** [RUG-IDS/Course-2017#16]
In the bonus section of Assigment 3 you mention a certain paper, refered as "Paper by Cover". Could you please provide the whole reference so that we can find the paper?
Thank you.

**Comment by rm-bwana** [comment]
Hi,
The information is in the Wiki tab of this repository. At the top you should find Code | Issues | Pull requests | Projects | **Wiki** | etc.
The link has been posted there.

**Comment by marialeyva** [comment]
Thank you.
