### ISSUE TITLE
Question regarding visualization

### ISSUE THREAD

**Issue by Daemonstool** [RUG-IDS/Course-2017#19]
I got a question regarding the feedback obtained during the presentation. I was advised to give the clusters from the reduced data set images and the clusters in the original data set images the same color.  However since you have to train every time on a different reduced dataset size, it is impossible to determine which clusters in the clustering on reduced images data set corresponds to the clusters in the images that show the clustering on the original dataset. Especially when the clusters computed using a reduced data set is way off to the clustering found with the original data.

I would like to know your opinion. 

I do understand that it is a bit hard to compare the clusters computed with the reduced dataset and the clusters computed with the full dataset, however I think the differences can be seen with a closer look.

![results_kmeans_clustering](https://user-images.githubusercontent.com/3306616/30780723-3ea969b2-a112-11e7-9f07-d5e367b9fcce.png)

Kind regards,
Henry

**Comment by rm-bwana** [comment]
Hello Henry,

May I assume the visualisations were created using Matlab? (If not the following may not be fully relevant).

In Matlab there are two ways of going about it. Firstly, you could try and specify the colours directly in the visualisation code. This may take a bit of trial and error to get right. Secondly, there is a way to create and store colours to be used in a visualisation later which can then help you ensure that they might be consistent. 

If all else fails: add a legend. Even if you just call it 'cluster 1' and 'cluster 2' we will see that it is the same cluster as before.

Rob.

**Comment by Daemonstool** [comment]
Thank you for your reponse. 

The entire problem is however that the clusters obtained using the reduced dataset deviate from the clusters that arise if using the original dataset. This means that you can't really compare the clusters unless you have some distance metric between the clusters to use to check how far the centroids are away from each other in both simulations. 

Kind regards,
Henry

**Comment by Daemonstool** [comment]
I already solved it by comparing the distances of each cluster in the reduced data set with the clusters in the original dataset. Based on this distance, the reduced data set clusters will get the same color as the clusters in the original data set cluster. 
[10.pdf](https://github.com/RUG-IDS/Course-2017/files/1327229/10.pdf)
[20.pdf](https://github.com/RUG-IDS/Course-2017/files/1327230/20.pdf)
[50.pdf](https://github.com/RUG-IDS/Course-2017/files/1327231/50.pdf)

**Comment by Daemonstool** [comment]
I believe this is what was meant with the feedback.
