### ISSUE TITLE
Missing csv file first assignment

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#2]
Could the movievalue.csv file be uploaded on Nestor? I cannot find it anywhere.

Thanks :)

Wouter

**Comment by jasperdev** [comment]
I got it from one of the previous year's repos, e.g. https://github.com/RUG-IDS/team-12_2016/tree/master/Assignment_1/DataSource . But I guess that solution will be gone soon after this message...

**Comment by mircealungu** [comment]
Err. This year's data is different. And the last year's projects are not supposed to be visible :) Let us upload the data for this year first :)

**Comment by mircealungu** [comment]
Here's the new file: 
https://github.com/RUG-IDS/Course-2017/blob/master/Assignments/movievalue.csv
