### ISSUE TITLE
Assignment 4, ex 1.4

### ISSUE THREAD

**Issue by TengXu94** [RUG-IDS/Course-2017#20]
in the forth exercise of the first part in the Assignment 4 we are asked to find all Rules with a minimum support of 0.3 and a minimum confidence of 0.7.
Now, from what I understood a rule is defined as an implication of the form X -> Y and
Support is just s an indication of how frequently the itemset appears in the dataset.
My question is: How can we apply support for a Rule?

**Comment by lutydlitatova** [comment]
@TengXu94 
From what I understand we apply the algorithm like in the slides - first find frequent itemsets and then find rules with high confidence from that. I was also confused but I believe this is how it's meant.

Ludmila

**Comment by joelgrondman** [comment]
Indeed you are right, here's a corrected version of the exercise: Find all rules with a minimum confidence of 0.7 that apply on an itemset with minimum support of 0.3.

**Comment by mircealungu** [comment]
@lutydlitatova and @joelgrondman are right. when we talk about the support of a rule, we imply the support of the corresponding itemset.

**Comment by TengXu94** [comment]
Thank you everyone, now it's more logical !
