### ISSUE TITLE
Self-joining

### ISSUE THREAD

**Issue by jasperdev** [RUG-IDS/Course-2017#22]
Hi,

I am a bit confused by the self-joining example on slide 22. I do understand why the following two itemsets are selected:
- **abcd** from **abc** and **abd**
- **acde** from **acd** and **ace**

but do not understand the third:
- **abce** from **abc** and **ace**

since ab != ac

**Comment by joelgrondman** [comment]
Each character represents an item and a string in this case is an itemset e.g. abce is an itemset.
In this case the characters in the string have simply been ordered alphabetically, abce, abec, ceab all represent the same itemset.

The overlap in symbolic characters has no meaning in this case, the self-joining function is simply a way of generating itemsets that are one item larger.

**Comment by jasperdev** [comment]
The overlap does have meaning in self-joining right? e.g. ["in pass k, the first k - 2 items must match"](http://www2.cs.uregina.ca/~dbd/cs831/notes/itemsets/itemset_apriori.html)

[slide 19 in this pdf](https://paginas.fe.up.pt/~ec/files_0506/slides/04_AssociationRules.pdf)

**Comment by joelgrondman** [comment]
The algorithm you are referring to generates itemsets that are 1 item larger in the previous iteration in a different algorithm. 

You can be very crude in generating 4-itemsets: given L3 = {abs, abd, acd, ace, bcd} we can create 4-itemsets by simply recombining all different items:  {abcd. abce. acde. bcde}. Pruning will get rid of the itemsets that do not have enough support without actually calculating their support.

All but itemset abcd is kept in C4 as all other itemsets has no sub itemset of size 3 that occurs in L3, hence not enough support.

The overlap algorithm in the link causes less 4-itemsets to be generated which makes the algorithm more efficient but results in the same C4 set after pruning.

The method in the slides looks at overlap of items no matter the position causing more 4-itemsets to be found before pruning.

**Comment by jasperdev** [comment]
Ok, thanks for clarifying
