### ISSUE TITLE
Eigen value decomposition + ANOVA

### ISSUE THREAD

**Issue by TimmermanIDS** [RUG-IDS/Course-2017#24]
Hi,

We have some questions about question 2.1a. We know that somebody else already posted an issue, but still we'd like to ask.

Does the eigen value decomposition mean that we should do a PCA with 186 dimensions? Also, how does ANOVA relate to this assignment. We're not sure how ANOVA can be applied to this problem. ANOVA tries to find significant differences between groups. Should we consider each feature to be a group? Also, should we do a post hoc test to check which features significantly differ in the set of features?

Kind regards,
Team 9

**Comment by sreejita-rug** [comment]
Hi,

1) ANOVA can be used for univariate analysis. Taking one feature at a time for one way ANOVA (you can also use univariate logistic regression for this) will give you a p-value which is a measure of the significance of that particular feature. You have a 2 class problem (healthy vs AML); the features are not to be considered as groups. When you enter the input data as : i-th feature in all the samples (or say just the labelled samples, or a representative dataset- whatever you choose), where i=1 to 186,  ANOVA will tell you whether this i-th feature leads to significant difference between the groups. If you had seen the slides on DREAM challenge in class you might have gotten an idea about this. The analysis shown in class with the boxplots showing the variances between the 2 classes for most significant features and least significant features is something you can do (the post hoc analysis to check whether the features found 'significant' by ANOVA are really significant and how). 

2) Eigen values and PCA: In MATLAB atleast you can choose to use pca, or eig or svd. In R also there are a few functions for pca. However if you are using tSNE with all 186 features and just the labelled part of the dataset tSNE _might_ treat the 186 features as 186 samples and 179 samples to be the features. You can select the top N significant features (where N< sample size) to perform tSNE.

**Comment by kbunte** [comment]
Dear Team 9,

there are several parts in that assignment where PCA can be a useful design choice dependent on how you use it. In 2.1a you are instructed to perform descriptive and exploratory tasks one of them is getting an idea about the approximate intrinsic dimensionality of the problem. The eigenvalues corresponding to the maximum variance directions extracted by PCA tell you how much variance of the data is explained when you use only the eigenvectors corresponding to the leading x eigenvalues. This provides useful information for preprocessing later. How much an individual feature contributes to the data variance is a bit more tricky and not asked here ... instead you should use ANOVA to rate the significance of the individual features. The groups are the classes healthy and AML.
