### ISSUE TITLE
Assignment 1.2 c unclear

### ISSUE THREAD

**Issue by sboelkens** [RUG-IDS/Course-2017#25]
Hello,

In question 1.2 c you ask:
_For a3, which is a continuous attribute, compute the information gain for every possible split._

What do you exactly mean by 'every possible split'? Do you consider only binary splits, or do you mean different numbers of splits (binary, 3-way, 4-way, etc), or even both? Because 'every possible split' feels like a lot of splits.

**Comment by rm-bwana** [comment]
Yes I would agree. Every single possible split would be a lot. Thankfully the overall question focuses only on binary splits when it says:

_"Consider the following set of training examples for a **binary** classification problem and **potential binary splits** on the attributes:"_

Therefore we only require you to have to create binary splits of the continuous attribute by using <= and > or < and >=. First example would be a split with x <= 1 down one branch and x > 1 down the other.  

If anything is still unclear or you have further questions feel free to ask.
