### ISSUE TITLE
Regarding the number of exercises 

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#28]
Hi TA's / Teachers,

For us there is some unclarity regarding the amount of exercises that we have to make. In the introductory slides it is stated that there are 7 assignments and that you need to pass all - 1 to complete the assignment part of the course. But there are 8 topics during the course. Does this mean that all -1 = 7 or is 1 topic skipped? 

Thank you in advance :)

Wouter

**Comment by Formsma** [comment]
If I remember correctly they said in the first lecture that there would be at least 7 exercises, and depending on the time left an 8th exercise would follow.

**Comment by rm-bwana** [comment]
Hi,

This topic is currently being agreed upon and we hope to have a concrete answer by the end of the week/early next week. I hope this will still be a reasonable time to answer your question.

Rob.

**Comment by rm-bwana** [comment]
Hello again,

I can confirm that there will only be 7 assignments. You are currently working on the 6th one and the 7th one should be released on Monday next week after the lecture on clustering.

Please note that in the timetable there is a time reserved as 'presentations' in the final tutorial (27 Oct). We are currently working on what structure this exactly will take but it will unlikely count towards the pass all-1 criteria. Note that me saying this is not legally binding until confirmed by the lecturers. Once we have finalised the structure an announcement will be made on Nestor.
