### ISSUE TITLE
Question about Part 2

### ISSUE THREAD

**Issue by TimmermanIDS** [RUG-IDS/Course-2017#29]
Dear TAs

I have two short questions about part 2 of this week's assignment.

First of all, what is exactly meant with "Create a TF.IDF representation of your corpus" in part 2.1? Does this simply mean that we should make a program that can calculate TD.IDF values, or is it something different? In other words, is it the thing you have to do in order to be able to make parts 2.2 and 2.3?

Secondly, in part 2.3 it is stated that searching for the string "story with the girl falling into a rabbit hole" should result in Alice in Wonderland. Is it required that this exact string gives Alice in Wonderland? The problem I'm having is that the part where the girl falls into the rabbit hole is only a very brief part of the entire story, and it's therefore quite difficult to link Alice in Wonderland to it. If I search for "Story about a girl, a rabbit and a queen" though, I'm able to find Alice in Wonderland much easier.

Kind regards,

Roland Timmerman

**Comment by joelgrondman** [comment]
To answer 2.1: yes you should make a program that can calculate TD.IDF values, these TD.IDF values are related to the corpus so they can be used to represent your corpus. It would also be recommended to use this representation for part 2.2 and 2.3.

2.3: if the query "story with the girl falling into a rabbit hole" does not result in Alice in Wonderland then this most likely indicates that your function was not implemented correctly. Remember that it should return the most likely text that matches the description or a list if there is no clear hit.

**Comment by TimmermanIDS** [comment]
Thank you for your answer.

I'm still not quite sure what is expected from us with part 2.1 in the report. Could you elaborate on that?

Also, am I correct in understanding that for part 2.3 we are not required to have Alice in Wonderland as the best match? I currently have it as third in the list, closely following two other books. Is that acceptable as well?

**Comment by mircealungu** [comment]
For the dilemma with Alice? What are your best two hits? Maybe they make
sense for your corpus :)

**Comment by TimmermanIDS** [comment]
I can't recall the second one right now, but the first one was Bryant's stories.

**Comment by joelgrondman** [comment]
Our intention with 2.1 was to be the first step towards executing 2.2 and 2.3 which is converting the corpus to TF.IDF values giving words in each text in the corpus a value representing its importance. This will prove useful for 2.2 and 2.3.
Now for the presentation of the TF.IDF values I can suggest a ranking of most important words for each text with the associated TF.IDF value.

**Comment by TimmermanIDS** [comment]
Isn't that exactly what we are supposed to do for 2.2?

**Comment by joelgrondman** [comment]
It's just a suggestion, we just want you to be able to succesfully obtain TF.IDF values from your corpus.
By representing the TF.IDF values we have an indication whether you succeeded in obtaining them or not.

**Comment by TimmermanIDS** [comment]
Thank you very much for the suggestion. I'm just a bit confused about what I should write in the report. It seems to me that if we are able to do 2.2 properly, then that means that our work for 2.1 should be good as well, right? Can we just say something like "We've written a function in Python that can calculate TF.IDF values. See part 2.2 and 2.3 for demonstrations of this."?

**Comment by joelgrondman** [comment]
No, you should definitely create some representation using your TF.IDF values. I understand it overlaps with 2.2 a little so surprise us with your representation!

**Comment by TimmermanIDS** [comment]
Ah alright, thank you.

Finally, the question about part 2.3. For the first example, do we have to find Alice in Wonderland as the best match, or is it also okay if it is high in the list of other likely options?

**Comment by joelgrondman** [comment]
That depends on your corpus and your implementation of your search engine. 
I haven't written that specific part of the assignment but you could take the example as a hint or guideline on how your implementation should function.
