### ISSUE TITLE
encoding moviefile

### ISSUE THREAD

**Issue by rm-bwana** [RUG-IDS/Course-2017#3]
Question from a group: 

We noticed that the encoding of the movie list file is messed up. In a normal client / contractor setting I would ask the client (you) for a better version. Another option would be to skip the unreadable movie titles.

**Comment by rm-bwana** [comment]
You may occasionally encounter data which is in a less than ideal format. We have left it this way to see how you will handle such challenges. How you do so is up to you as long as you explain why.

Therefore as a 'client' I only say that I have no better version. Apologies.

**Comment by mircealungu** [comment]
Goed. Next time, ask the group to send the question directly here on GH @rm-bwana !
