### ISSUE TITLE
Part 1.5

### ISSUE THREAD

**Issue by lutydlitatova** [RUG-IDS/Course-2017#30]
Dear all,

for question 1.5 in this weeks Assignment, before performing dimensionality reduction, we commonly normalize the data with tf-idf (e.g. before computing SVD). I just want to check I am on the right track with this approach, since tf-idf is only "introduced" in Part 2.

Thanks,
Ludmila

**Comment by joelgrondman** [comment]
Seems like a good idea. Of course you're free to use another technique to normalize the data. Just be sure to provide commentary on why the specific normalization method is appropriate.
