### ISSUE TITLE
1.2. Best-fitting Zipf distribution 

### ISSUE THREAD

**Issue by danielmlow** [RUG-IDS/Course-2017#31]
What do you mean by Best-fitting Zipf distribution?

I fit each distribution to a powerlaw. Then I compare it to a power law and an exponential distribution. 
![image](https://user-images.githubusercontent.com/14787791/31557732-475fe292-b04a-11e7-84a9-782fdd481ae2.png)
The first value R, which is the loglikelihood ratio between the two candidate distributions. This number will be positive if the data is more likely in the first distribution, and negative if the data is more likely in the second distribution. The second value (third column) is the significance value for that direction is p. 
So here we see that Hamlet is the closest to its powerlaw fit. Is this correct?

**Comment by joelgrondman** [comment]
I can recommend to take a look at the text analysis slides again, in particular page 25. Zipf's law doesn't just stick to the rigid rule of a frequency of approximately 1/i of the most frequent item for item i. In general it can follow the rule of 1/i^n. See this wikipedia page for a more detailed description and references: https://en.wikipedia.org/wiki/Zipf%27s_law

**Comment by danielmlow** [comment]
Okay, thanks!
