### ISSUE TITLE
Generating trigrams

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#32]
Hi all,

Should the trigrams be generated after the cleaning up the data or should the trigrams be generated from the raw data? The cleaned data I can imagine create 'nicer' trigrams but the raw data would ofcourse be a better representation of the data. 

Wouter

**Comment by rm-bwana** [comment]
Hi Wouter,

This depends on how you clean the data. Trigrams which include punctuation aren't really interesting. So you can do it after you remove those (or ignore those, however you want to implement it).

Thereafter, it is up to you as a team to decide how strict you want to stem/lemmatise the text. Do you actually see any differences between the raw data and the 'cleaned' data?
