### ISSUE TITLE
Comparing the books with zips law

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#33]
Hi all,

We plotted zipfs law (1/n^(1.07)) and the word distribution of all the documents in loglog scales. Although they all seem to follow the same pattern as zips law they all (ofcourse) have a different starting position. Is this something we should normalize or is this ok?

**Comment by joelgrondman** [comment]
Zips law can predict the frequency of the ith ranked term based on the law (1/n^(1.07)) and the frequency of the first word. Did you specify the frequency of the first word?

**Comment by rm-bwana** [comment]
Also remember that it is nearly impossible to find a text which perfectly fits zipfs law. It will always have some small deviation one way or the other. 

Do you notice an improvement if you normalise it?
