### ISSUE TITLE
Assignment 7: 2.4 measures for comparing linkages

### ISSUE THREAD

**Issue by RoosWesterbeek** [RUG-IDS/Course-2017#36]
I'm using the Cophenetic Correlation Coefficient to compare the different kind of linkages. Are there other kind of measures I can use to compare the linkages?

**Comment by joelgrondman** [comment]
The slides mention other techniques briefly (up to you to find out what they mean) and Cophenetic Correlation Coefficient as well. You could also compare linkages through visualization of their result. E.g. silhouettes after a set amount splits/merges or other constraint has been reached. The dendrogram itself can also be used for comparison up to a point.

Be sure to describe the measure you are using and why you think the measurement is relevant in this case.
