### ISSUE TITLE
Presentations

### ISSUE THREAD

**Issue by bogdanp05** [RUG-IDS/Course-2017#37]
Hi,

Regarding the presentations on Friday, will a subject be presented twice by 2 different teams or will there be a common presentation, where each team presents sections of that assignment?

Regards,
Team 7 and Team 11

**Comment by rm-bwana** [comment]
Hello,

We have assigned roughly 10min per team (we are not going to be too strict with time, these are more guidelines than rules). 

If both your teams want to agree to present a certain part of the assignment in more detail while the other teams chooses another part that is also acceptable. 

The priority of these presentations is to provide an explanation to your fellow students more than how well you can make a presentation about your assignment.

All the best.
Rob.
