### ISSUE TITLE
Unknown data

### ISSUE THREAD

**Issue by TimmermanIDS** [RUG-IDS/Course-2017#6]
Hi,

For part 1.2 it is asked to clean the data, and enrich it with three extra columns. We've used the OMDb API to both get the three extra columns and try to see if it can replace some of the unknown values in the movievalues.csv file. However, we can't fill in all the values. Especially the budgets and revenues are uncommon information. We'd like to know if it is necessary to know all the data about at least 1000 movies, or if it is sufficient to only add the three extra columns for at least 1000 movies, and just replace unknown values where possible. I hope I've formulated that question clearly.

Thanks in advance!

**Comment by rm-bwana** [comment]
Yes. It is not likely that you will find all information for every single movie. You may choose to leave out these movies or not. 

One thing to note is that in Ex. 1.4 you will be required to perform some descriptive analysis on the information you have gathered. If you perform such an analysis with data which is incomplete you may be limited in what you can analyse or get results that do not actually describe the data (this is a cardinal sin in Data Science). 

We leave it up to you how to overcome this challenge but I would suggest you do not compromise yourself by having too few over too many.
