### ISSUE TITLE
Using the book

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#8]
Hey,

Should the book be used merely as reference or is there a clear path through the book? If there is, which is it? It could help students prepare for the exam. 

For example; I read chapter 2 which seems to follow the first lecture nicely. However I do not know whether the end of chapter 2 (measures of similarity) will be questioned during the exam.

**Comment by rm-bwana** [comment]
My understanding of the course is that the book is merely a reference and not a strict how to guide. But I would recommend you wait for @mircealungu or @kbunte  to confirm/deny it.

**Comment by mircealungu** [comment]
You should think of the book as extra material and a possible source to go to if you need to fill in with more details information than you can find in the lecture. 

There will be sometimes great overlap between the lectures with the book, and sometimes the materials in the lectures will be based on other sources. 

Finally, if a topic is not touched during the lectures, it will not be in the exam.
